package aaatemporary;

import java.util.Arrays;
import java.util.List;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import jlogg.shared.LogLine;

public class LoremIpsum {

	public static final List<String> getLines() {
		return Arrays.asList("Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
				"Donec pulvinar odio ut sem mollis, sed gravida nisl vulputate.",
				"Nulla placerat magna sed consequat egestas.",
				"Maecenas imperdiet est id ex feugiat, in feugiat ligula dignissim.",
				"Ut faucibus odio in sem faucibus condimentum.", "Praesent ut lorem ut nibh pharetra dignissim.",
				"Nulla eu risus aliquet, molestie nisl id, tristique eros.",
				"Duis quis ante quis libero rhoncus viverra a et orci.",
				"Phasellus ac nulla eget metus condimentum fermentum.",
				"Proin laoreet nunc eu elit volutpat, nec imperdiet lorem egestas.",
				"Donec maximus enim vitae dolor faucibus ornare.",
				"Maecenas sed orci nec turpis semper maximus volutpat ac felis.",
				"Pellentesque fermentum turpis ullamcorper facilisis sollicitudin.",
				"Proin id purus quis neque facilisis consequat.",
				"Vivamus ut felis sollicitudin, euismod metus ac, pulvinar felis.",
				"Sed eu libero sit amet justo convallis dictum.",
				"Proin et augue placerat, suscipit sapien eu, feugiat nisl.",
				"Suspendisse sollicitudin nisi quis eleifend consequat.",
				"Vivamus vel massa vulputate, congue ex eget, sodales nisl.",
				"Phasellus auctor libero pretium mi porttitor, vel pulvinar justo faucibus.",
				"Mauris sagittis nisl ac suscipit porttitor.",
				"Pellentesque suscipit nibh eget massa laoreet pulvinar.",
				"Sed sit amet elit sagittis, eleifend quam at, congue lacus.",
				"Nam tristique tellus et leo mattis, eu malesuada purus molestie.",
				"Etiam malesuada nibh eu est rhoncus, in posuere est posuere.",
				"Maecenas porttitor ante sit amet sollicitudin malesuada.",
				"Aliquam pellentesque ipsum eget mauris volutpat lobortis.",
				"Nullam tristique justo non nisi viverra pellentesque condimentum at odio.",
				"Etiam tincidunt metus id turpis sodales, sed cursus purus sollicitudin.",
				"Nullam in justo at magna vestibulum dignissim et laoreet quam.",
				"Aliquam non est scelerisque ex commodo laoreet.",
				"Sed vel magna a sapien efficitur pharetra at in massa.",
				"Curabitur aliquam neque nec gravida venenatis.", "Mauris hendrerit lectus vel consequat placerat.",
				"Cras sed libero consectetur, convallis dolor eu, eleifend urna.",
				"Cras rutrum felis laoreet, ullamcorper ante ac, placerat nibh.",
				"Aenean at neque ac nunc scelerisque dapibus.",
				"Integer non nulla id erat sodales vestibulum non vitae urna.", "Nulla cursus mi at sem cursus cursus.",
				"Donec cursus felis id felis dignissim scelerisque.", "Nam convallis nunc et velit pulvinar porta.",
				"Vivamus volutpat lacus a augue faucibus, non tincidunt eros imperdiet.",
				"Curabitur fringilla nisi sit amet ullamcorper eleifend.",
				"Vivamus pulvinar mi eget dolor pulvinar, eget rhoncus neque auctor.",
				"Aliquam commodo urna vel dolor pretium aliquam.", "Proin et tortor vel libero facilisis congue.",
				"Suspendisse volutpat augue quis sem pulvinar porttitor.", "Fusce vel eros vel quam blandit suscipit.",
				"Ut accumsan orci ac vulputate vestibulum.",
				"Suspendisse quis dolor consequat, rhoncus eros sed, elementum felis.",
				"Vestibulum non tortor in odio posuere posuere lacinia commodo erat.",
				"Vestibulum convallis diam suscipit tortor ornare tincidunt.",
				"Praesent rhoncus nisl et magna tristique, at aliquet quam euismod.",
				"Phasellus sit amet orci id metus aliquam ullamcorper.",
				"Fusce fermentum leo et lorem maximus elementum.",
				"Curabitur nec neque varius, imperdiet ligula ac, auctor ex.",
				"Nam hendrerit lacus vitae tortor blandit blandit.", "Proin id quam at sapien tristique consectetur.",
				"Curabitur quis mauris ac augue hendrerit tempus.", "Cras dictum neque sed sem cursus vehicula.",
				"Vivamus blandit libero ornare sodales vulputate.",
				"Nulla ut diam at urna ultrices ultricies id et leo.", "Fusce hendrerit magna id commodo dignissim.",
				"Praesent vitae ex ornare, posuere dui nec, consequat odio.",
				"Sed id mauris fringilla, elementum diam quis, efficitur lorem.",
				"Pellentesque pellentesque libero at laoreet congue.",
				"Praesent pharetra neque at tortor eleifend aliquet.", "Sed molestie enim id rhoncus porta.",
				"Nam tincidunt augue sit amet leo laoreet, a aliquam lacus lobortis.",
				"Donec eu justo quis nulla laoreet cursus.",
				"Praesent vel est tristique, gravida magna sit amet, molestie diam.",
				"Morbi et massa quis lectus vehicula porttitor.", "Aenean elementum sem et nisl tempus molestie.",
				"Curabitur aliquet mi eu elit pharetra, a tincidunt mi suscipit.",
				"Phasellus pellentesque nulla eget elit hendrerit, id hendrerit sem congue.",
				"Nulla mollis urna non orci ultrices congue.", "Integer vel libero at sem auctor facilisis et id nisi.",
				"Curabitur placerat leo at turpis sagittis fringilla.",
				"Suspendisse vitae ligula sit amet lorem dapibus fermentum et pulvinar felis.",
				"Praesent hendrerit mauris ac enim condimentum facilisis.",
				"Proin nec felis maximus, volutpat libero viverra, maximus metus.",
				"Suspendisse eget ante ac erat vulputate consectetur et a magna.",
				"Maecenas a diam placerat, gravida nisl sed, viverra velit.",
				"Nam ut odio cursus, accumsan odio et, iaculis elit.", "Fusce facilisis nunc sed rhoncus efficitur.",
				"Maecenas sollicitudin nulla ac ligula dapibus suscipit.",
				"Mauris ullamcorper erat in porttitor vestibulum.", "Cras dictum purus sit amet ultrices rhoncus.",
				"Aenean viverra mauris id libero scelerisque, euismod eleifend dui semper.",
				"Sed sit amet sem vel arcu auctor lacinia vel ut augue.", "Proin laoreet metus a accumsan porttitor.",
				"Nunc sit amet tortor vel nunc sodales tempus.",
				"Sed molestie velit non leo tincidunt, quis commodo lacus ultrices.",
				"Duis dictum nibh ut nunc ullamcorper interdum.",
				"Aenean at ante nec dolor cursus ultricies et sit amet ante.",
				"Praesent eu est vel urna porta aliquet.", "Fusce sollicitudin velit eget scelerisque tristique.",
				"Duis laoreet justo lobortis risus varius interdum.",
				"Sed tincidunt nunc ut arcu scelerisque, sit amet vulputate sem venenatis.",
				"Nulla id leo nec quam tincidunt scelerisque.", "Ut finibus augue a imperdiet fermentum.",
				"Ut placerat lorem non lectus tincidunt molestie.", "Sed nec turpis sed velit egestas interdum.",
				"Proin nec arcu tempus, ornare ante eget, laoreet nibh.",
				"Maecenas vitae metus scelerisque, interdum ipsum vitae, ultricies velit.",
				"Ut lobortis ex ac sagittis scelerisque.", "Vestibulum eleifend magna sed mi porta vulputate.",
				"Aenean vestibulum arcu sit amet malesuada feugiat.", "Proin at quam ac felis commodo tempor.",
				"Suspendisse non quam vel felis sollicitudin bibendum.",
				"Vivamus et erat varius, varius purus vitae, mollis eros.",
				"Integer congue nibh posuere blandit molestie.", "Ut lacinia mi a consequat posuere.",
				"Duis ut massa sit amet urna egestas maximus quis vel est.",
				"Ut et orci tempus, malesuada eros sed, euismod felis.",
				"Ut sit amet leo vitae mauris dapibus feugiat eget et eros.",
				"Cras eu enim a diam ultrices lacinia et at metus.",
				"Phasellus auctor sapien eu velit vehicula, eu pulvinar justo dapibus.",
				"Sed lacinia eros ut tortor imperdiet accumsan.", "Fusce at lectus vel nisi pulvinar commodo.",
				"Cras porta mi non molestie semper.", "Fusce vitae risus sit amet felis tincidunt commodo.",
				"Etiam fringilla lorem quis metus auctor, at dictum velit venenatis.",
				"Vestibulum molestie erat sit amet justo finibus fermentum.",
				"Nunc rhoncus nibh ac sapien tincidunt, eget placerat mauris sollicitudin.",
				"Morbi ut libero vel orci euismod aliquam.",
				"Cras sit amet risus semper, dapibus quam sed, tincidunt massa.",
				"In rutrum mi id magna consequat dignissim.", "Sed nec augue a elit tempor maximus.",
				"Nullam gravida ipsum a hendrerit efficitur.", "Maecenas tempor sapien ut velit ornare egestas.",
				"Morbi at ante volutpat, ornare nibh ut, pellentesque felis.",
				"In quis arcu non turpis suscipit eleifend a ut dolor.",
				"Vestibulum vitae eros elementum turpis fermentum fringilla vitae pretium enim.",
				"Aliquam lobortis velit ac imperdiet imperdiet.", "Ut vitae metus eu orci convallis venenatis.",
				"Nunc ut quam varius, lacinia neque a, mattis velit.",
				"Integer tempus tellus ut mauris accumsan, nec sagittis neque elementum.",
				"Vestibulum lobortis leo in risus consectetur, sit amet pellentesque augue sodales.",
				"Curabitur in dolor et nisl feugiat suscipit.",
				"Aenean nec lacus ut magna aliquam tincidunt in eu arcu.",
				"Vivamus eleifend nisi venenatis quam sagittis, a fermentum diam ultricies.",
				"Morbi sollicitudin mauris ut odio auctor tempor.",
				"Vivamus vehicula enim eu eros aliquet elementum quis id libero.",
				"Nulla ac lorem vitae dui varius ultrices.",
				"Vivamus ut enim condimentum, porttitor ante non, consectetur libero.",
				"Morbi ut nisi at metus suscipit congue ullamcorper vitae dui.",
				"Donec laoreet diam eu tellus bibendum ullamcorper.",
				"Aliquam in risus rhoncus, varius erat eget, commodo purus.",
				"Duis tempor dolor in ipsum porttitor, malesuada tempor purus sodales.",
				"Aenean finibus velit at urna sollicitudin efficitur.",
				"Maecenas blandit massa mollis nisl egestas, quis ullamcorper ipsum porta.",
				"Suspendisse vitae urna vitae ipsum commodo fringilla sit amet et velit.",
				"Pellentesque mattis lorem sit amet turpis tincidunt, sed tincidunt nisi maximus.",
				"Nulla accumsan est auctor felis dapibus ultricies.",
				"Nunc blandit lorem eget felis mollis, quis pulvinar justo consectetur.",
				"Aliquam commodo nunc ac consequat vehicula.",
				"Etiam id ipsum vitae ex eleifend fringilla sed rhoncus justo.",
				"Cras aliquet tellus eget tortor interdum euismod.",
				"Integer sodales dolor dignissim consectetur volutpat.",
				"Curabitur id nisi non felis aliquam scelerisque.",
				"Suspendisse placerat augue ut lectus elementum rutrum.",
				"Vestibulum scelerisque justo vel urna porta, eu fringilla leo laoreet.",
				"Generated 50 paragraphs, 1221 words, 9043 bytes of Lorem Ipsum");
	}

	public static final ObservableList<LogLine> getLogLines() {
		ObservableList<LogLine> lines = FXCollections.observableArrayList();
		for (int i = 0; i < getLines().size(); i++) {
			lines.add(new LogLine(i));
		}

		return lines;
	}
}
