name: Test Mac OS Build
on:
  workflow_dispatch
  
jobs:
  macos_aarch64_build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.1.0
        with:
          distribution: adopt
          java-version: 17
      - name: Get Details
        run: mvn enforcer:display-info
      - name: Set Release Version
        run: mvn --batch-mode versions:set -DnewVersion="3.0.3"
      - name: Maven Build
        run: mvn -B clean package
      - name: Rename output
        run: mv target/jpackage/JLogg-3.0.3.dmg target/jpackage/JLogg-aarch64-3.0.3.dmg
      - name: Upload
        uses: actions/upload-artifact@v2.2.2
        with:
          name: macos-aarch64
          path: target/jpackage/JLogg*.dmg
        
  macos_x64_build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.1.0
        with:
          distribution: adopt
          java-version: 17
      - name: Get Details
        run: mvn enforcer:display-info
      - name: Set Release Version
        run: mvn --batch-mode versions:set -DnewVersion="3.0.3"
      - name: Maven Build
        run: mvn -B clean package
      - name: Rename output
        run: mv target/jpackage/JLogg-3.0.3.dmg target/jpackage/JLogg-x86_64-3.0.3.dmg
      - name: Upload
        uses: actions/upload-artifact@v2.2.2
        with:
          name: macos-x64
          path: target/jpackage/JLogg*.dmg
