name: Test Build
on:
  workflow_dispatch
  
jobs:
  windows_portable_build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.1.0
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
      - name: Set Release Version
        run: mvn --batch-mode versions:set -DnewVersion="${{ env.VERSION }}"
      - name: Maven Build
        run: mvn -B "-Dbuild.isportable=true" clean package
      - name: Create Portable Zip
        run: Compress-Archive -Path target/JLogg/* -Destination target/JLogg-${{ env.VERSION }}.zip
      - name: Upload
        uses: actions/upload-artifact@v4.6.2
        with:
          name: windows
          path: target/JLogg*.zip
