name: Test Mac OS Build
on:
  workflow_dispatch
  
jobs:
  macos_build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup Java
        uses: actions/setup-java@v2.1.0
        with:
          distribution: adopt
          java-version: 17
          
      - name: Maven Build
        run: mvn -B clean package
