name: Test Mac OS Build
on:
  workflow_dispatch
  
jobs:
  macos_build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.1.0
        with:
          distribution: temurin
          java-version: 17
      - name: Set Release Version
        run: mvn --batch-mode versions:set -DnewVersion="${{ github.ref_name }}"
      - name: Maven Build
        run: mvn -B clean package
      - name: pack
        run: jpackage --dest /Users/runner/work/jlogg/jlogg/target/jpackage --type dmg --app-version 3.0.0 --name JLogg --module jlogg/jlogg.Launcher --module-path /Users/runner/work/jlogg/jlogg/target/modules/junit-platform-commons-1.9.1.jar:/Users/runner/work/jlogg/jlogg/target/modules/junit-platform-engine-1.9.1.jar:/Users/runner/work/jlogg/jlogg/target/modules/gson-2.10.1.jar:/Users/runner/work/jlogg/jlogg/target/modules/junit-jupiter-engine-5.9.1.jar:/Users/runner/work/jlogg/jlogg/target/modules/junit-jupiter-api-5.9.1.jar:/Users/runner/work/jlogg/jlogg/target/modules/jlogg-master.jar:/Users/runner/work/jlogg/jlogg/target/modules/apiguardian-api-1.1.2.jar:/Users/runner/work/jlogg/jlogg/target/modules/opentest4j-1.2.0.jar 
        
    
