name: Release
on:
  workflow_dispatch:
jobs:
  windows_build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 15
          
      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore
      - name: Maven Build
        run: mvn -B clean package
      - name: Store Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save
      - name: JPackage
        run: jpackage -t msi -n JLogg -p target/modules -m jlogg/jlogg.Launcher --win-dir-chooser --file-associations log.properties
        
      - name: Upload
        uses: actions/upload-artifact@v2.2.2
        with:
          name: JLogg.msi
          path: JLogg*.msi
        
  macos_build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 15
          
      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore
      - name: Maven Build
        run: mvn -B clean package
      - name: Store Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save
      - name: JPackage
        run: jpackage -t DMG -n JLogg -p target/modules -m jlogg/jlogg.Launcher --file-associations log.properties
        
      - name: Upload
        uses: actions/upload-artifact@v2.2.2
        with:
          name: JLogg.dmg
          path: JLogg*.dmg
