name: Release JLogg

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  update_maven_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.1.0
        with:
          distribution: temurin
          java-version: 17
      - name: Set Release Version
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Update maven version 
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          mvn --batch-mode versions:set -DnewVersion=$RELEASE_VERSION

  windows_build:
    runs-on: windows-latest
    needs: [update_maven_version]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.1.0
        with:
          distribution: temurin
          java-version: 17
    
      - name: Maven Build
        run: mvn -B clean package
      
      - name: Upload
        uses: actions/upload-artifact@v2.2.2
        with:
          name: windows
          path: target/jpackage/JLogg*.msi

  macos_build:
    runs-on: macos-latest
    needs: [update_maven_version]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.1.0
        with:
          distribution: temurin
          java-version: 17
          
      - name: Maven Build
        run: mvn -B clean package
  
      - name: Upload
        uses: actions/upload-artifact@v2.2.2
        with:
          name: macos
          path: target/jpackage/JLogg*.dmg

  release:
    runs-on: ubuntu-latest
    needs: [windows_build,macos_build]
    steps:
      - name: Download Builds
        uses: actions/download-artifact@v2.0.8
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files:
            ./windows/JLogg-1.0.msi 
            ./macos/JLogg-1.0.dmg 
  
