name: Release
on:
  push:
    branches: 
    - master
jobs:
  windows_build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup Java
        uses: actions/setup-java@v2.1.0
        with:
          distribution: adopt
          java-version: 16
          
      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore
      - name: Maven Build
        run: mvn -B clean package
      - name: Store Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save
      - name: JPackage
        run: jpackage -t msi -n JLogg -p target/modules -m jlogg/jlogg.Launcher --win-dir-chooser --file-associations log.properties
        
      - name: Upload
        uses: actions/upload-artifact@v2.2.2
        with:
          name: windows
          path: JLogg*.msi
        
  macos_build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup Java
        uses: actions/setup-java@v2.1.0
        with:
          distribution: adopt
          java-version: 16
          
      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore
      - name: Maven Build
        run: mvn -B clean package
      - name: Store Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save
      - name: JPackage
        run: jpackage -t DMG -n JLogg -p target/modules -m jlogg/jlogg.Launcher --file-associations log.properties
        
      - name: Upload
        uses: actions/upload-artifact@v2.2.2
        with:
          name: macos
          path: JLogg*.dmg

  release:
    runs-on: ubuntu-latest
    needs: [windows_build,macos_build]
    steps:
      - name: Download Builds
        uses: actions/download-artifact@v2.0.8
      - name: Automatic Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN}}"
          automatic_release_tag: "continuous"
          title: "Continuous Build"
          files: |
            ./windows/*
            ./macos/*
        
    
