name: Release JLogg

on:
  workflow_dispatch:
    inputs:
      majorVersion:
        description: "Major Version Number"
        required: true
        type: number
      minorVersion:
        description: "Minor Version Number"
        required: true
        type: number
      bugfixVersion:
        description: "Bugfix Version"
        required: true
        type: number

env:
  JAVA_VERSION: 21
  VERSION: "${{ inputs.majorVersion }}.${{ inputs.minorVersion }}.${{ inputs.bugfixVersion }}"

jobs:
  deploy_package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.1.0
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
      - name: Set Release Version
        run: mvn --batch-mode versions:set -DnewVersion="${{ env.VERSION }}"
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows_build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.1.0
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
      - name: Set Release Version
        run: mvn --batch-mode versions:set -DnewVersion="${{ env.VERSION }}"
      - name: Maven Build
        run: mvn -B "-Dbuild.isportable=false" clean package
      - name: Upload
        uses: actions/upload-artifact@v4.6.2
        with:
          name: windows
          path: target/JLogg*.msi

  macos_aarch64_build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.1.0
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
      - name: Set Release Version
        run: mvn --batch-mode versions:set -DnewVersion="${{ env.VERSION }}"
      - name: Maven Build
        run: mvn -B -Dbuild.isportable=false clean package
      - name: Rename output
        run: mv target/JLogg-${{ env.VERSION }}.dmg target/JLogg-aarch64-${{ env.VERSION }}.dmg
      - name: Upload
        uses: actions/upload-artifact@v4.6.2
        with:
          name: macos-aarch64
          path: target/JLogg*.dmg
          
  macos_x64_build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.1.0
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
      - name: Set Release Version
        run: mvn --batch-mode versions:set -DnewVersion="${{ env.VERSION }}"
      - name: Maven Build
        run: mvn -B -Dbuild.isportable=false clean package
      - name: Rename output
        run: mv target/JLogg-${{ env.VERSION }}.dmg target/JLogg-x86_x64-${{ env.VERSION }}.dmg
      - name: Upload
        uses: actions/upload-artifact@v4.6.2
        with:
          name: macos-x64
          path: target/JLogg*.dmg
  release:
    runs-on: ubuntu-latest
    needs: [windows_build,macos_aarch64_build,macos_x64_build,deploy_package]
    steps:
      - name: Download Builds
        uses: actions/download-artifact@v4.2.1
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN}}"
          automatic_release_tag: "${{ env.VERSION}}"
          prerelease: false
          files: |
            ./windows/*
            ./macos-aarch64/*
            ./macos-x64/*
  
